### ISSUE TITLE
Enhancements for repetitive work

### ISSUE THREAD

**Issue by rahul286** [rtCamp/Frappe-Manager#102]
Inside `fm shell`, we mostly do

- [x] Set work dir to `~/frappe-bench`.
- [ ] Set `bench use <sitename>` to the name of `fm create <sitename>` as all bench commands we use for that site. Might change once we have multisite.

On host machine
- [ ] `fm reset <sitename>` which does `bench reinstall` and restore sitename and setup config.

**Comment by Xieyt** [comment]
>  * [x]  Set work dir to `~/frappe-bench`.

Implemented in #131.
