### ISSUE TITLE
Update command fails post migration

### ISSUE THREAD

**Issue by dhsathiya** [rtCamp/Frappe-Manager#169]
**Describe the bug**
Update command fails post migration
```sh
% fm update
❌ Error Occured  [Errno 2] No such file or directory: '/Users/devarshi/frappe/sites/apps.localhost/bench_config.toml'
🔍 More info about error is logged in /Users/devarshi/frappe/logs/fm.log
```

**To Reproduce**
- Update frappe-manager.
- `fm list`
- fm update bench-name

**Expected behavior**
There should be a `bench_config.toml` in the bench directory.

**System information (please complete the following information):**
- [ ] `fm --version` -- 0.13.2
- [ ] `lsb_release -a` -- MacOs 14.4.1 (23E224)
- [ ] `docker version` -- 
```
% docker version
Client:
 Cloud integration: v1.0.35+desktop.4
 Version:           24.0.6
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        ed223bc
 Built:             Mon Sep  4 12:28:49 2023
 OS/Arch:           darwin/arm64
 Context:           desktop-linux

Server: Docker Desktop 4.23.0 (120376)
 Engine:
  Version:          24.0.6
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.7
  Git commit:       1a79695
  Built:            Mon Sep  4 12:31:36 2023
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.6.22
  GitCommit:        8165feabfdfe38c65b599c4993d227328c231fca
 runc:
  Version:          1.1.8
  GitCommit:        v1.1.8-0-g82f18fe
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```
- [ ] `docker-compose version` or `docker compose version` `Docker Compose version v2.21.0-desktop.1`

**Attach log**
Provided over a private medium

**Comment by Xieyt** [comment]
As I can see in the logs this happened because of a bug in migration where the migration executor was not able correctly working when there was migration failure for a site.
