### ISSUE TITLE
Supervisorctl is not running in frappe service

### ISSUE THREAD

**Issue by sudhegan** [rtCamp/Frappe-Manager#175]
**Describe the bug**
cannot start the site for development after stopping
due to error as below
Supervisorctl is not running in frappe service

**To Reproduce**
1.create a site then stop thew site
2. code the site
3. then stop the site
4. the start the site it won't start 

**Expected behavior**
site should start

**System information (please complete the following information):**
- [ 0.13.3 ] `fm --version`
- [ Fedora Linux 40 (KDE Plasma) ] `lsb_release -a`
- [ 26.1.2 ] `docker version`
- [ ] `docker-compose version` or `docker compose version`

**Attach log**
Please attach logs from `~/frappe/logs/fm.log` for faster resolution.
[fm.log](https://github.com/rtCamp/Frappe-Manager/files/15285711/fm.log)

**Additional context**

**Comment by Xieyt** [comment]
This issue arises due to a bug. The error occurs because fm fails to detect whether supervisord is running when one of its processes is not in the running state.

**Comment by sudhegan** [comment]
is the already in work or this is the first time and a bug in supervisor or fm

**Comment by Xieyt** [comment]
This bug is being fixed in #177. The bug is present in `fm` not in supervisord.
