### ISSUE TITLE
❌ Error Occured  devl.lh : Supervisorctl is not running in frappe service

### ISSUE THREAD

**Issue by sudhegan** [rtCamp/Frappe-Manager#191]
This issue tracker is only for issues related to Frappe-Manager. Please use https://github.com/rtcamp/frappe-manager/discussions for support questions.

**Describe the bug**
 cannot start site 
**To Reproduce**
1. Run command 'fm start {sitename}'
2. See error
❌ Error Occured  devl.lh : Supervisorctl is not running in frappe service
**Expected behavior**

**System information (please complete the following information):**
- [0.14.0 ] `fm --version`
- [ Fedora Linux 40 (KDE Plasma)] `lsb_release -a`
- [26.1.3 ] `docker version`
- [1.29.2 ] `docker-compose version` or `docker compose version`

**Attach log**
Please attach logs from `~/frappe/logs/fm.log` for faster resolution.
[fm.log](https://github.com/user-attachments/files/15775782/fm.log)

**Additional context**

**Comment by Xieyt** [comment]
Seems like supervisord in the frappe container is not able to start.  Will need more logs to debug it further
@sudhegan Please share frappe container logs using this command `docker compose -f ~/frappe/sites/devl.lh/docker-compose.yml logs frappe`

**Comment by sudhegan** [comment]
here is the log output

`devllh-frappe  | Setting up user
devllh-frappe  | usermod: no changes
devllh-frappe  | UID and GID updated successfully.
devllh-frappe  | wait-for-it: waiting 120 seconds for global-db:3306
devllh-frappe  | wait-for-it: global-db:3306 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-cache:6379
devllh-frappe  | wait-for-it: devllh-redis-cache:6379 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-queue:6379
devllh-frappe  | wait-for-it: devllh-redis-queue:6379 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-socketio:6379
devllh-frappe  | wait-for-it: devllh-redis-socketio:6379 is available after 0 seconds
devllh-frappe  | Environment: dev
devllh-frappe  | Configuring frappe dev server
devllh-frappe  | Traceback (most recent call last):
devllh-frappe  |   File "<frozen runpy>", line 189, in _run_module_as_main
devllh-frappe  |   File "<frozen runpy>", line 112, in _get_module_details
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in <module>
devllh-frappe  |     @whitelist(methods=["POST", "PUT"])
devllh-frappe  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/__init__.py", line 862, in innerfn
devllh-frappe  |     from frappe.utils.typing_validations import validate_argument_types
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 7, in <module>
devllh-frappe  |     from pydantic import ConfigDict
devllh-frappe  | ImportError: cannot import name 'ConfigDict' from 'pydantic' (/workspace/frappe-bench/env/lib/python3.11/site-packages/pydantic/__init__.py)
devllh-frappe  | Setting up user
devllh-frappe  | usermod: no changes
devllh-frappe  | UID and GID updated successfully.
devllh-frappe  | wait-for-it: waiting 120 seconds for global-db:3306
devllh-frappe  | wait-for-it: global-db:3306 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-cache:6379
devllh-frappe  | wait-for-it: devllh-redis-cache:6379 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-queue:6379
devllh-frappe  | wait-for-it: devllh-redis-queue:6379 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-socketio:6379
devllh-frappe  | wait-for-it: devllh-redis-socketio:6379 is available after 0 seconds
devllh-frappe  | Environment: dev
devllh-frappe  | Configuring frappe dev server
devllh-frappe  | Traceback (most recent call last):
devllh-frappe  |   File "<frozen runpy>", line 189, in _run_module_as_main
devllh-frappe  |   File "<frozen runpy>", line 112, in _get_module_details
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in <module>
devllh-frappe  |     @whitelist(methods=["POST", "PUT"])
devllh-frappe  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/__init__.py", line 862, in innerfn
devllh-frappe  |     from frappe.utils.typing_validations import validate_argument_types
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 7, in <module>
devllh-frappe  |     from pydantic import ConfigDict
devllh-frappe  | ImportError: cannot import name 'ConfigDict' from 'pydantic' (/workspace/frappe-bench/env/lib/python3.11/site-packages/pydantic/__init__.py)
devllh-frappe  | Setting up user
devllh-frappe  | usermod: no changes
devllh-frappe  | UID and GID updated successfully.
devllh-frappe  | wait-for-it: waiting 120 seconds for global-db:3306
devllh-frappe  | wait-for-it: global-db:3306 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-cache:6379
devllh-frappe  | wait-for-it: devllh-redis-cache:6379 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-queue:6379
devllh-frappe  | wait-for-it: devllh-redis-queue:6379 is available after 0 seconds
devllh-frappe  | wait-for-it: waiting 120 seconds for devllh-redis-socketio:6379
devllh-frappe  | wait-for-it: devllh-redis-socketio:6379 is available after 0 seconds
devllh-frappe  | Environment: dev
devllh-frappe  | Configuring frappe dev server
devllh-frappe  | Traceback (most recent call last):
devllh-frappe  |   File "<frozen runpy>", line 189, in _run_module_as_main
devllh-frappe  |   File "<frozen runpy>", line 112, in _get_module_details
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/__init__.py", line 1442, in <module>
devllh-frappe  |     @whitelist(methods=["POST", "PUT"])
devllh-frappe  |      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/__init__.py", line 862, in innerfn
devllh-frappe  |     from frappe.utils.typing_validations import validate_argument_types
devllh-frappe  |   File "/workspace/frappe-bench/apps/frappe/frappe/utils/typing_validations.py", line 7, in <module>
devllh-frappe  |     from pydantic import ConfigDict
devllh-frappe  | ImportError: cannot import name 'ConfigDict' from 'pydantic' (/workspace/frappe-bench/env/lib/python3.11/site-packages/pydantic/__init__.py)`

**Comment by Xieyt** [comment]
Your `frappe` package is broken. There might be issue with required deps in frappe not available in env or frappe code is broken as shown in the above log.

Using the below command you can open your site shell, then use bench commands to fix the frappe issue.
`docker compose -f ~/frappe/sites/devl.lh/docker-compose.yml run --rm --user frappe --entrypoint zsh --workdir /workspace/frappe-bench frappe`

**Comment by sudhegan** [comment]
thanks the above cmd opened a shell for the bench and after running `bench setup requirements` the problem solved it showed a warning `''ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
pygls 0.10.2 requires pydantic<1.9,>=1.7, but you have pydantic 2.7.3 which is incompatible.''` but the site started successfully is the warning important and reported to frappe?

**Comment by Xieyt** [comment]
The above warning occurs when two python packages depend on same library but their is version difference between two. Specifically, pygls 0.10.2 requires pydantic versions between 1.7 and 1.9, but you have pydantic 2.7.3 installed, which is outside this range. While your site has started successfully, such conflicts can potentially lead to runtime errors or unexpected behavior, so it's a good practice to address them.
