### ISSUE TITLE
Nginx 503 Service Temporarily Unavailable

### ISSUE THREAD

**Issue by lalitmohanyh** [rtCamp/Frappe-Manager#232]
![screenshot-erp_yenehealth_com-2024_09_06-19_18_02](https://github.com/user-attachments/assets/292ff35e-d8f4-4c7e-a814-b7312cdc5866)

After creating an app getting this with IP or Qualified Domain

I also updated the `default.conf` located in. `/frappe/sites/yenehealth.localhost/configs/nginx/conf/conf.d`

<img width="1792" alt="image" src="https://github.com/user-attachments/assets/31becf1c-82fb-428d-98fc-90be6169492d">

Restart the App using `fm restart <sitename>`

**Comment by meichthys** [comment]
@lalitmohanyh Would you mind sharing what the solution was to this?
