### ISSUE TITLE
pip install error: externally managed environment

### ISSUE THREAD

**Issue by ashish-greycube** [rtCamp/Frappe-Manager#239]
![image](https://github.com/user-attachments/assets/ad17a0be-f8b6-441f-a12b-11c0173686a7)
pl guide how to proceed

**Comment by ashish-greycube** [comment]
@dhsathiya your input will help. thanks

**Comment by Xieyt** [comment]
This will work - `pip install --break-system-packages`

**Comment by ashish-greycube** [comment]
thanks @Xieyt  it works
