### ISSUE TITLE
Pulling Docker Images Failed

### ISSUE THREAD

**Issue by NagariaHussain** [rtCamp/Frappe-Manager#72]
Tried to run `fm create fm2.localhost --apps erpnext:version-15`:

![CleanShot 2023-12-08 at 06 47 47@2x](https://github.com/rtCamp/Frappe-Manager/assets/34810212/623a27e1-3b68-4c74-98d1-a8c020174495)

Docker Desktop is installed and running, don't know why this is failing? Maybe we can show a more specific error message?

Machine: MacBook Pro M1 Pro

**Comment by NagariaHussain** [comment]
Pulling some image manually works:

![CleanShot 2023-12-08 at 06 52 58@2x](https://github.com/rtCamp/Frappe-Manager/assets/34810212/130df9a7-972d-41a5-8e11-ad485ddad654)

**Comment by Xieyt** [comment]
Could you review or share the logs located at `/home/<user>/frappe/logs/fm.log`? That willl contain the specific error causing the above issue.

**Comment by NagariaHussain** [comment]
```
DEBUG:  nginx Error 
[2023-12-08 06:47:45,187] DEBUG:  frappe Error 
[2023-12-08 06:47:45,189] DEBUG:  mailhog Error 
[2023-12-08 06:47:45,189] DEBUG:  adminer Error 
[2023-12-08 06:47:45,190] DEBUG:  mariadb Error 
[2023-12-08 06:47:45,191] DEBUG:  redis-queue Error 
[2023-12-08 06:47:45,192] DEBUG: Error response from daemon: Head "https://ghcr.io/v2/rtcamp/frappe-manager-nginx/manifests/v0.8.3": denied: denied
[2023-12-08 06:47:45,194] DEBUG: RETURN CODE: 18
[2023-12-08 06:47:45,194] 
```

You can find the complete log [here](https://platform.buildwithhussain.dev/files/fm.log).

**Comment by NagariaHussain** [comment]
Also, it will be good if it shows a message like "Check logs at ~/frappe/logs/fm.log" for more info" when setup fails.

**Comment by Xieyt** [comment]
> ```
> DEBUG:  nginx Error 
> [2023-12-08 06:47:45,187] DEBUG:  frappe Error 
> [2023-12-08 06:47:45,189] DEBUG:  mailhog Error 
> [2023-12-08 06:47:45,189] DEBUG:  adminer Error 
> [2023-12-08 06:47:45,190] DEBUG:  mariadb Error 
> [2023-12-08 06:47:45,191] DEBUG:  redis-queue Error 
> [2023-12-08 06:47:45,192] DEBUG: Error response from daemon: Head "https://ghcr.io/v2/rtcamp/frappe-manager-nginx/manifests/v0.8.3": denied: denied
> [2023-12-08 06:47:45,194] DEBUG: RETURN CODE: 18
> [2023-12-08 06:47:45,194] 
> ```
> 
> You can find the complete log [here](https://platform.buildwithhussain.dev/files/fm.log).

When you're logged into the Docker ghcr.io registry and your GitHub Personal Access Token (PAT) has expired, you'll encounter this issue. There are two solutions available, so choose the one that suits you best:
    - Log out of the Docker ghcr.io registry by executing this command: `docker logout ghcr.io` then rerun fm command.
    OR
    - Generate a new PAT, use it for re-login into ghcr.io, and then rerun fm command.
