### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by CJignesh01** [rtCamp/Frappe-Manager#82]
fm: Unable to open /dev/radio0: No such file or directory

**Comment by Xieyt** [comment]
Can you provide more detailed info as how it occurred, what is your operating system, python version and if possible fm.log ?

**Comment by CJignesh01** [comment]
docker service is running , but still not able to create site
![Screenshot from 2023-12-22 13-03-52](https://github.com/rtCamp/Frappe-Manager/assets/125439762/9e60f1f7-7f77-4dd1-9746-8ff59f073d62)
![Screenshot from 2023-12-22 13-03-52](https://github.com/rtCamp/Frappe-Manager/assets/125439762/6e39b7a2-bf09-4711-88a1-007a7e28ed95)

**Comment by CJignesh01** [comment]
> Can you provide more detailed info as how it occurred, what is your operating system, python version and if possible fm.log ?

Python 3.10.12
ubuntu22.04

**Comment by washaqq** [comment]
i had same issue and fixed; https://github.com/rtCamp/Frappe-Manager/issues/83

**Comment by SujinIn** [comment]
I’ve solved this problem

1. Create the docker group.
`sudo groupadd docker`

2. Add the user to the docker group.
`sudo usermod -aG docker jignesh`
→ this **jignesh** is user name

3. Log out and log back in to ensure docker runs with correct permissions.
Start docker.
`sudo service docker start`
→ I just do reboot.
