### ISSUE TITLE
Starting docke containers failed

### ISSUE THREAD

**Issue by mazizij** [rtCamp/Frappe-Manager#86]
This issue tracker is only for issues related to Frappe-Manager. Please use https://github.com/rtcamp/frappe-manager/discussions for support questions.

**Describe the bug**
Docker containers fail to start
**To Reproduce**
1. Run command 'fm -v create frappe'
2. See error
![image](https://github.com/rtCamp/Frappe-Manager/assets/40990516/ffec8c1b-7d86-4174-84cb-811e5015a427)

**Expected behavior**
That containers would start

**System information (please complete the following information):**
- [ 0.9.0] `fm --version`
- [No LSB modules are available.
Distributor ID:	Pop
Description:	Pop!_OS 22.04 LTS
Release:	22.04
Codename:	jammy
 ] `lsb_release -a`
- [Client:
 Version:           24.0.6-rd
 API version:       1.43
 Go version:        go1.20.7
 Git commit:        da4c87c
 Built:             Wed Sep  6 16:41:53 2023
 OS/Arch:           linux/amd64
 Context:           desktop-linux

Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
 ] `docker version`
- [Docker Compose version v2.2.3 ] `docker-compose version` or `docker compose version`

**Attach log**
Please attach logs from `~/frappe/logs/fm.log` for faster resolution.
[fm.log](https://github.com/rtCamp/Frappe-Manager/files/13767241/fm.log)

**Additional context**

**Comment by Xieyt** [comment]
Please run this command `fm create frappes` and share the contents of the fm.log once again.

**Comment by mazizij** [comment]
> Please run this command `fm create frappes` and share the contents of the fm.log once again.

I get the same error.

[fm.log](https://github.com/rtCamp/Frappe-Manager/files/13775698/fm.log)

**Comment by Xieyt** [comment]
@mazizij Update docker compose cli and it will start working.

**Comment by mazizij** [comment]
@Xieyt , thanks it is working.
