### ISSUE TITLE
Despite sucessfull installation site does not start

### ISSUE THREAD

**Issue by sternbj** [rtCamp/Frappe-Manager#98]
This issue tracker is only for issues related to Frappe-Manager. Please use https://github.com/rtcamp/frappe-manager/discussions for support questions.

![image](https://github.com/rtCamp/Frappe-Manager/assets/150677945/7d55d6fb-3dfa-40e4-8a6c-9c542f324bd4)

**To Reproduce**
las commands:
![image](https://github.com/rtCamp/Frappe-Manager/assets/150677945/91182535-4ef4-4f14-bc34-97fd877d2294)

**Expected behavior**
starting ERPNext

**System information (please complete the following information):**
- [ 0.9.0] `fm --version`
- [ ] `lsb_release -a`
-~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

- [ ] `docker version`
- [ ] Server: Docker Desktop 4.26.1 (131620)
 Engine:
  Version:          24.0.7
  API version:      1.43 (minimum version 1.12)
  Go version:       go1.20.10
  Git commit:       311b9ff
  Built:            Thu Oct 26 09:08:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.25
  GitCommit:        d8f198a4ed8892c764191ef7b3b06d8a2eeb5c7f
 runc:
  Version:          1.1.10
  GitCommit:        v1.1.10-0-g18a0cb0
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

- [ ] `docker-compose version` or `docker compose version`
...-Series:~$ docker-compose version` or `docker compose version
or: command not found
Command 'docker-compose' not found, but can be installed with:
sudo snap install docker          # version 20.10.24, or
sudo apt  install docker-compose  # version 1.29.2-1
See 'snap info docker' for additional versions.

**Attach log**
Please attach logs from `~/frappe/logs/fm.log` for faster resolution.
Sorry do not know how to get it. I But I will if you tell me. Since it's on docker i think it's not as "easy" as normal terminal.

**Additional context**
never was able tot start ERPNext. Did mor or less same procedue on my mac and it worked.

**Comment by Xieyt** [comment]
@sternbj The log file is on the host machine not in the docker containers and is located at `~/frappe/logs/fm.log`. 
You can view the log using command the command`cat ~/frappe/logs/fm.log`.
Please provide the log file so that I can better debug the issue.

After starting the site wait for like ~ 1-2 min( this doesn't happen always).

**Comment by sternbj** [comment]
Sorry you are right easy to find. Even on UI

[fm.log](https://github.com/rtCamp/Frappe-Manager/files/13959515/fm.log)

**Comment by Xieyt** [comment]
@sternbj As I can see in the log fm was not able to create site properly because of network issue in the site creation. 
This is a bug in fm that it's not able to alert user that the site is broken, there is already an issue #96 and is fixed in #91. 
Fix will be available in next release.

Till then:
- Delete the previous site. `fm delete erpnext`
- Now again create the site. `fm create erpnext`

**Comment by sternbj** [comment]
Sorry but this does not work. It worked with a new site but unfortunatelly I just did not inst
[fm.log](https://github.com/rtCamp/Frappe-Manager/files/13974492/fm.log)
all the apps, i deleted again and now I cant make it run at all, though no issues when instaling

**Comment by sternbj** [comment]
So I figured out, that I can install A site, but if I add the apps in the create command, sites are not reachable in the end. So can I add apps later? I am sorry for this question, but I do not know very much about this stuff.

**Comment by Xieyt** [comment]
@sternbj You can easily add apps later using the `bench get-app <appname>` command.

**Comment by Xieyt** [comment]
Closing this issue, since checking of site after site creation has already been implemented.
