### ISSUE TITLE
Not available on Chromebook's Debian Bullseye

### ISSUE THREAD

**Issue by monolithonadmin** [rtCamp/Frappe-Manager#99]
Hello I tried to install it on my machine, but I got this:

ERROR: Could not find a version that satisfies the requirement frappe-manager (from versions: none)
ERROR: No matching distribution found for frappe-manager

Client: Docker Engine - Community
 Version:           24.0.7
 Docker Compose version v2.21.0

Any help much appreciated. Thank you

**Comment by Xieyt** [comment]
@monolithonadmin Try installing it using this command `pip install -U git+https://github.com/rtCamp/Frappe-Manager`.
